#!/bin/sh

set -ex

exec 2>&1

# Mitigate crash looping
sleep 60

IMAGES=/isodevice/iconograph
mkdir -p "${IMAGES}"

BOOT=/isodevice

FLAGS=$(cat flags)

while :; do
  ./fetcher.py --image-dir="${IMAGES}" --ca-cert=../config/ca.cert.pem ${FLAGS}
  ./update_grub.py --image-dir="${IMAGES}" --boot-dir="${BOOT}" > ${BOOT}/grub/grub.cfg.tmp && mv ${BOOT}/grub/grub.cfg.tmp ${BOOT}/grub/grub.cfg
  sleep 3600
done
