#!/bin/sh

set -ex

exec 2>&1

# Mitigate crash looping
sleep 60

IMAGES=/isodevice/iconograph
mkdir -p "${IMAGES}"

FLAGS=$(cat flags)

while :; do
  ./fetcher.py --image-dir="${IMAGES}" --ca-cert=../config/ca.cert.pem ${FLAGS}
  sleep 3600
done
